### ISSUE TITLE
Error at fetchData (view-5...

### ISSUE THREAD

**Issue by GuyGallant1** [stephanrauh/ngx-extended-pdf-viewer#2989]
1st error: is https://www.condogestionsupport.com/condo11/assets/locale/en-US/viewer.ftl 404 (Not Found)
              Within the server the viewer.ftl exists. IIS has been configurated to handle mime: ftl. All folders within the root
               folder  C:\inetpub\CondoWebSite are being accessed properly. The application works everywhere. Except           
               when viewing a pdf. The pdf is view properly (good stuff)
However there is another error showned when I check the console (when doing an inspect)

chunk-DZZMZ7NA.js:23 ERROR Error
    at fetchData (viewer-5.3.749.mjs:7597:13)
    at async genericl10n_GenericL10n._createBundle (viewer-5.3.749.mjs:34507:16)
    at async genericl10n_GenericL10n._generateBundles (viewer-5.3.749.mjs:34493:20)

What causes this error.
I am working with Angulat 20.1.3

**Comment by stephanrauh** [comment]
That's weird. Did you try to open the *.ftl file in the browser? Maybe it really doesn't exist, although you already checked that. But maybe the browser thinks differently?

When I saw that you reference a public web site, I tried to find the file myself. It looks like the assets folder is not there. Maybe you're using the new `public` folder instead of the `assets` folder? But that's just a wild shot.

As for the MIME type - https://pdfviewer.net/extended-pdf-viewer/troubleshooting suggest to use the MIME type `text/plain`. I don't think that makes any difference, but you never know.

```
<mimeMap fileExtension=".ftl" mimeType="text/plain" />
```

**Comment by majora2007** [comment]
I'm getting this exact error:

404 https://demo.kavitareader.com/assets/locale/en-US/viewer.ftl

I have confirmed the file is there from the wwwroot:

<img width="651" height="147" alt="Image" src="https://github.com/user-attachments/assets/4b642230-5ac8-4b6c-b4f5-ae34a7fb56f0" />

This seems to be some regression as it was working in a previous version of the library (I just updated a few months ago from an older build).

**Comment by stephanrauh** [comment]
@majora2007 As far as I can see, the file is really missing on the server. The error message is a 404.

@majora2007 @GuyGallant1 
Maybe you're using a broken copy of ngx-extended-pdf-viewer. Have a look at your node_modules folder. It should look like the two screenshots. It's a wild shot, but I wonder if the subfolders of the locale folders are missing. That's weird because both https://demo.kavitareader.com/assets/locale/locale.json and https://www.condogestionsupport.com/condo11/assets/locale/locale.json are there. It's just the subfolders I can't reach via the browser.

<img width="384" height="737" alt="Image" src="https://github.com/user-attachments/assets/4debe248-79e9-4d99-8868-b0bfd359a490" />

<img width="298" height="865" alt="Image" src="https://github.com/user-attachments/assets/2d8e3d53-a47c-4079-b236-749737f8c7cb" />

**Comment by majora2007** [comment]
I am matching yours for both node_modules and the dist build. I'm on version 24.1.0

**Comment by stephanrauh** [comment]
Well, version 24.1.0 contains the correct folder structure:
https://app.unpkg.com/ngx-extended-pdf-viewer@24.1.0/files/assets/locale/en-US

**Comment by GuyGallant1** [comment]
Sorry it took so long for replying, but forced vacation.

Anyways I upgraded to version  5.3.750 and I am still getting the 
following error message.
The actual pdf does view in the pdf-viewer.  Its just that I don't like 
to have warnings that I do not understand

Regards
Guy

**Comment by stephanrauh** [comment]
Can you check if the file is on the server?

I'm still puzzled why you can download
   https://www.condogestionsupport.com/condo11/assets/locale/locale.json
but not
  https://www.condogestionsupport.com/condo11/assets/locale/en-US/viewer.ftl

Either your server refuses to send *.ftl files, or the file isn't there. 

I'm closing this issue now because it doesn't seem to be a problem of the library. Nonetheless, I'm still listening when you add comments.

Best regards,
Stephan

**Comment by GuyGallant1** [comment]
Hi,

The file exists on the server. I believe that its either an IIS issue (I 
did implement your suggestion) or
a security issue on the folder. For now every thing works ok. I am not 
sure what I am missing when I get those warnings?
For now I do have bigger issues to solve.

Thanks anyways.
Guy Gallant

**Comment by majora2007** [comment]
I fixed this issue on my end, it was indeed my backend (ASP.NET) not allowing sending ftl. 

@GuyGallant1 since you mentioned IIS, if you're using UseStaticFiles middleware, this is what I have (for this library explicitly):
```cs
app.UseStaticFiles(new StaticFileOptions
        {
            // bcmap files needed for PDF reader localizations (https://github.com/Kareadita/Kavita/issues/2970)
            // ftl files are needed for PDF zoom options (https://github.com/Kareadita/Kavita/issues/3995)
            ContentTypeProvider = new FileExtensionContentTypeProvider
            {
                Mappings =
                {
                    [".bcmap"] = "application/octet-stream",
                    [".ftl"] = "text/plain"
                }
            },
```

**Comment by stephanrauh** [comment]
@majora2007 Thanks for sharing your insight with us! I was a bit worried because two developers reported the same error, and I couldn't reproduce it. I'm glad you've sorted it out, and I hope that it also help @GuyGallant1 to get rid of the bug!

**Comment by GuyGallant1** [comment]
Just to let you know. I have applied the patch to program.cs.
Now the errors have gone away.

I would suggest that you add to your documentation, this patch could be 
applied for .Net core projects.

Thanks,
Guy Gallant

**Comment by stephanrauh** [comment]
I've added the code snippet and a description of the bug here: https://pdfviewer.net/extended-pdf-viewer/troubleshooting

Please check if I got it right.

Thanks in advance,
Stephan
