### ISSUE TITLE
Will the ngx-extended-pdf-viewer 11.0.0 require Ivy?

### ISSUE THREAD

**Issue by ShotiQ** [stephanrauh/ngx-extended-pdf-viewer#1066]
I'm currently using Angular 10 with ivy disabled. After updating this library in my project from 10.5.0 to 11.0.0-alpha.13 and running npm start, I recieved this error

`ERROR in node_modules/ngx-extended-pdf-viewer/lib/document-properties/pdf-document-properties-overlay/pdf-document-properties-overlay.component.d.ts:6:21 - error TS2694: Namespace '"./node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

6     static ɵfac: i0.ɵɵFactoryDeclaration<PdfDocumentPropertiesOverlayComponent, never>;
                      ~~~~~~~~~~~~~~~~~~~~
node_modules/ngx-extended-pdf-viewer/lib/document-properties/pdf-document-properties-overlay/pdf-document-properties-overlay.component.d.ts:7:21 - error TS2694: Namespace '"./node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.

7     static ɵcmp: i0.ɵɵComponentDeclaration<PdfDocumentPropertiesOverlayComponent, "pdf-document-properties-overlay", never, {}, {}, never, never>;
                      ~~~~~~~~~~~~~~~~~~~~~~
node_modules/ngx-extended-pdf-viewer/lib/dynamic-css/dynamic-css.component.d.ts:20:21 - error TS2694: Namespace '"./node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.       

20     static ɵfac: i0.ɵɵFactoryDeclaration<DynamicCssComponent, never>;
                       ~~~~~~~~~~~~~~~~~~~~
node_modules/ngx-extended-pdf-viewer/lib/dynamic-css/dynamic-css.component.d.ts:21:21 - error TS2694: Namespace '"./node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.     

21     static ɵcmp: i0.ɵɵComponentDeclaration<DynamicCssComponent, "pdf-dynamic-css", never, { "zoom": "zoom"; "width": "width"; }, {}, never, never>;
7m                       ~~~~~~~~~~~~~~~~~~~~~~
node_modules/ngx-extended-pdf-viewer/lib/ngx-extended-pdf-viewer-common.module.d.ts:58:21 - error TS2694: Namespace '"./node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.   

58     static ɵfac: i0.ɵɵFactoryDeclaration<NgxExtendedPdfViewerCommonModule, never>;
                       ~~~~~~~~~~~~~~~~~~~~
node_modules/ngx-extended-pdf-viewer/lib/ngx-extended-pdf-viewer-common.module.d.ts:59:21 - error TS2694: Namespace '"./node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.  

59     static ɵmod: i0.ɵɵNgModuleDeclaration<NgxExtendedPdfViewerCommonModule, [typeof i1.DynamicCssComponent, typeof i2.PdfZoomDropdownComponent, typeof i3.PdfContextMenuComponent, typeof i4.PdfPresentationModeComponent, typeof i5.PdfOpenFileComponent, typeof i6.PdfPrintComponent, typeof i7.PdfDownloadComponent, typeof i8.PdfBookmarkComponent, typeof i9.PdfZoomToolbarComponent, typeof i10.PdfPagingAreaComponent, typeof i11.PdfFindbarComponent, typeof i12.PdfSidebarComponent, typeof i13.PdfHandToolComponent, typeof i14.PdfSelectToolComponent, typeof i15.PdfSecondaryToolbarComponent, typeof i16.PdfDocumentPropertiesOverlayComponent, typeof i17.PdfSearchInputFieldComponent, typeof i18.PdfFindPreviousComponent, typeof i19.PdfFindNextComponent, typeof i20.PdfFindInputAreaComponent, typeof i21.PdfFindbarOptionsTwoContainerComponent, typeof i22.PdfFindbarOptionsOneContainerComponent, typeof i23.PdfFindMatchCaseComponent, typeof i24.PdfFindHighlightAllComponent, typeof i25.PdfFindEntireWordComponent, typeof i26.PdfFindFuzzilyComponent, typeof i27.PdfFindMultipleSearchTextsComponent, typeof i28.PdfFindIgnoreAccentsComponent, typeof i29.PdfFindbarOptionsThreeContainerComponent, typeof i30.PdfFindResultsCountComponent, typeof i31.PdfFindbarMessageContainerComponent, typeof i32.PdfFindRangeComponent, typeof i33.PdfFindCurrentPageOnlyComponent, typeof i34.PdfToolbarComponent, typeof i35.PdfFindButtonComponent, typeof i36.PdfToggleSidebarComponent, typeof i37.PdfToggleSecondaryToolbarComponent, typeof i38.PdfLastPageComponent, typeof i39.PdfFirstPageComponent, typeof i40.PdfNextPageComponent, typeof i41.PdfPreviousPageComponent, typeof i42.PdfPageNumberComponent, typeof i43.PdfRotatePageComponent, typeof i44.PdfZoomInComponent, typeof i45.PdfZoomOutComponent, typeof i46.PdfDummyComponentsComponent, typeof i47.PdfSidebarContentComponent, typeof i48.PdfSidebarToolbarComponent, typeof i49.PdfOriginalComponent, typeof i50.PdfDarkThemeComponent, typeof i51.PdfLightThemeComponent, typeof i52.TranslatePipe], [typeof i53.CommonModule, typeof i54.FormsModule], [typeof i2.PdfZoomDropdownComponent, typeof i3.PdfContextMenuComponent, typeof i4.PdfPresentationModeComponent, typeof i5.PdfOpenFileComponent, typeof i6.PdfPrintComponent, typeof i7.PdfDownloadComponent, typeof i8.PdfBookmarkComponent, typeof i9.PdfZoomToolbarComponent, typeof i10.PdfPagingAreaComponent, typeof i11.PdfFindbarComponent, typeof i12.PdfSidebarComponent, typeof i47.PdfSidebarContentComponent, typeof i48.PdfSidebarToolbarComponent, typeof i15.PdfSecondaryToolbarComponent, typeof i16.PdfDocumentPropertiesOverlayComponent, typeof i17.PdfSearchInputFieldComponent, typeof i18.PdfFindPreviousComponent, typeof i19.PdfFindNextComponent, typeof i20.PdfFindInputAreaComponent, typeof i21.PdfFindbarOptionsTwoContainerComponent, typeof i22.PdfFindbarOptionsOneContainerComponent, typeof i23.PdfFindMatchCaseComponent, typeof i24.PdfFindHighlightAllComponent, typeof i25.PdfFindEntireWordComponent, typeof i27.PdfFindMultipleSearchTextsComponent, typeof i28.PdfFindIgnoreAccentsComponent, typeof i29.PdfFindbarOptionsThreeContainerComponent, typeof i30.PdfFindResultsCountComponent, typeof i31.PdfFindbarMessageContainerComponent, typeof i32.PdfFindRangeComponent, 
typeof i33.PdfFindCurrentPageOnlyComponent, typeof i13.PdfHandToolComponent, typeof i43.PdfRotatePageComponent, typeof i14.PdfSelectToolComponent, typeof i34.PdfToolbarComponent, typeof i35.PdfFindButtonComponent, typeof i36.PdfToggleSidebarComponent, typeof i37.PdfToggleSecondaryToolbarComponent, typeof i38.PdfLastPageComponent, typeof i39.PdfFirstPageComponent, typeof i40.PdfNextPageComponent, typeof i41.PdfPreviousPageComponent, typeof i42.PdfPageNumberComponent, typeof i44.PdfZoomInComponent, typeof i45.PdfZoomOutComponent, typeof i49.PdfOriginalComponent, typeof i50.PdfDarkThemeComponent, typeof i51.PdfLightThemeComponent, typeof i52.TranslatePipe, typeof i1.DynamicCssComponent, typeof i46.PdfDummyComponentsComponent]>;
                       ~~~~~~~~~~~~~~~~~~~~~
node_modules/ngx-extended-pdf-viewer/lib/ngx-extended-pdf-viewer-common.module.d.ts:60:21 - error TS2694: Namespace '"./node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.  

60     static ɵinj: i0.ɵɵInjectorDeclaration<NgxExtendedPdfViewerCommonModule>;

...`

So yeah, I was wondering if should I enable my project to use Ivy if using the new incoming version of this library?

**Comment by chetan592** [comment]
Got same issue when I upgraded to version 11. Ivy is disabled in my project.

**Comment by stephanrauh** [comment]
Yes, starting with Version 11, Ivy is required. I decided to activate Ivy because it's the default since Angular 9.

**Comment by stephanrauh** [comment]
Rule of thumb: I try to keep two years of backward compatibility.

**Comment by ShotiQ** [comment]
Ohh I guess ill upgrade then :D Thanks!
