### ISSUE TITLE
Cannot find module 'ngx-extended-pdf-viewer/lib/events/annotation-editor-layer-event' or its corresponding type declarations

### ISSUE THREAD

**Issue by rms2219** [stephanrauh/ngx-extended-pdf-viewer#2990]
After upgrading an Angular 19 project to Angular 20, we are no longer able to build. The build error is as follows:

>Cannot find module 'ngx-extended-pdf-viewer/lib/events/annotation-editor-layer-event' or its corresponding type declarations

We have an import in 2 separate components that are causing this error:

>import {AnnotationEditorEvent} from "ngx-extended-pdf-viewer/lib/events/annotation-editor-layer-event";

Both of these components worked fine in Angular 19.0.3.

**Version info**
- ^24.3.0

**Comment by rms2219** [comment]
Some additional information. I realized after I posted this that the upgrade to Angular 20 changed my `tsconfig.json` file.

>"moduleResolution": "node"

was changed to 

>"moduleResolution": "bundler"

This new value seems generates the error mentioned above when building. Using the old value allows for normal building.

**Comment by stephanrauh** [comment]
You're using a "deep import" - something that's frowned upon for reasons I keep forgetting. What happens if you do it this way?

```ts
import {AnnotationEditorEvent} from "ngx-extended-pdf-viewer";
```

**Comment by rms2219** [comment]
> You're using a "deep import" - something that's frowned upon for reasons I keep forgetting. What happens if you do it this way?
> 
> import {AnnotationEditorEvent} from "ngx-extended-pdf-viewer";

Another error:

>TS2724: '"ngx-extended-pdf-viewer"' has no exported member named 'AnnotationEditorEvent'. Did you mean 'AnnotationEditorType'?

Which is obviously weird since I can see that `AnnotationEditorEvent` is exported.

I think there might be an issue with the public API, though. It appears to be missing this, which I would need to do what you've suggested above:

```typescript
export * from './lib/events/annotation-editor-layer-event';
```

**Comment by stephanrauh** [comment]
That makes sense. Please update to version 24.3.1-alpha.1. It should fix your bug.

I've called it an alpha version because I've solved another bug that hits the layout of forms, and I need more time to make sure I've solved that bug for real. Apart from that, I believe that alpha version is production-ready.

**Comment by stephanrauh** [comment]
Let's close the issue. I suppose it's solved now.
