### ISSUE TITLE
ngx-extended-pdf-viewer v15.2.0 not working on iOS 13.0^

### ISSUE THREAD

**Issue by mkvashennikov** [stephanrauh/ngx-extended-pdf-viewer#1617]
**Describe the bug**
Any document does not open, errors come out in the console "i.addEventListener is not a function". Help me please fix this issue....

**Version info**
- 15.2.0
 
**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max iOS v 13.0

**Comment by stephanrauh** [comment]
iOS 13? No. I'm awfully sorry - and I don't wont to be disrespectful, but it's a security issue, and that's my number 1 priority these days. iOS 13 is an old version, and there's no reason to support outdated operating systems containing security bugs that can be exploited by hackers. If the bug still persists after updating your operating system to the latest version, I'm ready to help you.
